#!/usr/bin/env python3
"""Attribution hygiene over the commit history reachable from HEAD.

Provenance: re-implements, from documented behaviour only, the attribution
half of the commit-gate doctrine that the consolidation inventory of
2026-09-19 (section 6) marked as the smallest agent-skills increment to land
in paes. No text or code was copied. The rule itself lives in
``policies/contribution.md``; this module is its enforcement and the runtime
default lives in project settings. Standard library only.

Rules, one issue code each, applied to every line of every message:

- ``attribution-trailer``: a line that opens with ``Co-Authored-By:`` or
  ``Signed-off-by:`` (case-insensitive).
- ``generated-signature``: a line that opens, after optional symbols or
  whitespace, with ``generated with`` or ``generated by`` (any case, hyphen or
  space between the words).

Bot exemption (2026-10-07, brief tasks/kit-v14-sandbox-spec-and-bots.json): a
``Signed-off-by:`` line is skipped when the commit's author email is listed
under ``bot_authors`` in ``adapters/project-spec.yaml``, read through
``kit.parse_spec``; a missing file, a parse error or a missing key means an
empty list. ``Co-Authored-By:`` lines and generated-by signatures still fail
for bots. The email is not authenticated: the rule is history hygiene, not
access control. ``inspect_message`` called without an author stays strict.

Findings name the commit and the rule, never the offending line, so a report
can be quoted without repeating what it rejects.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

TRAILER_PATTERN = re.compile(r"^\s*(?:co-authored-by|signed-off-by)\s*:", re.IGNORECASE)
SIGNED_OFF_PATTERN = re.compile(r"^\s*signed-off-by\s*:", re.IGNORECASE)
SPEC = "adapters/project-spec.yaml"
GENERATED_PATTERN = re.compile(r"^[\W_]*generated[- ](?:with|by)\b", re.IGNORECASE)

RECORD_SEPARATOR = "\x00"
FIELD_SEPARATOR = "\x1f"


def inspect_message(message: str, author_email: str | None = None, bot_authors: tuple[str, ...] | list[str] = ()) -> list[str]:
    """Return the sorted, de-duplicated issue codes for one full commit message.

    When ``author_email`` is in ``bot_authors``, a ``Signed-off-by:`` line is skipped; nothing else is.
    """
    exempt = author_email is not None and author_email in bot_authors
    issues: set[str] = set()
    for line in message.splitlines():
        if exempt and SIGNED_OFF_PATTERN.match(line):
            continue
        if TRAILER_PATTERN.match(line):
            issues.add("attribution-trailer")
        if GENERATED_PATTERN.match(line):
            issues.add("generated-signature")
    return sorted(issues)


def read_history(root: Path) -> list[tuple[str, str, str]]:
    """Read (sha, author email, full message) for every commit reachable from HEAD."""
    result = subprocess.run(
        ["git", "log", "HEAD", "-z", f"--format=%H{FIELD_SEPARATOR}%ae{FIELD_SEPARATOR}%B"],
        cwd=root,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        if "does not have any commits yet" in result.stderr or "unknown revision" in result.stderr:
            return []
        raise RuntimeError(f"git log failed: {result.stderr.strip()}")
    commits: list[tuple[str, str, str]] = []
    for record in result.stdout.split(RECORD_SEPARATOR):
        if record:
            sha, email, message = record.split(FIELD_SEPARATOR, 2)
            commits.append((sha, email, message))
    return commits


def read_bot_authors(root: Path) -> tuple[str, ...]:
    """The ``bot_authors`` list of the project specification; empty when absent or unreadable."""
    path = root / SPEC
    if not path.is_file():
        return ()
    scripts = str(Path(__file__).resolve().parent)
    if scripts not in sys.path:
        sys.path.insert(0, scripts)
    import kit  # from scripts/
    try:
        spec = kit.parse_spec(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, ValueError):
        return ()
    value = spec.get("bot_authors")
    return tuple(value) if isinstance(value, list) else ()


def check_history(root: Path) -> dict[str, object]:
    """Inspect HEAD history and return a report with ``passed``, ``commits`` and ``findings``."""
    commits = read_history(root)
    bot_authors = read_bot_authors(root)
    findings = [
        {"commit": sha[:12], "rule": rule}
        for sha, email, message in commits
        for rule in inspect_message(message, email, bot_authors)
    ]
    return {"passed": not findings, "commits": len(commits), "findings": findings}


def main() -> int:
    parser = argparse.ArgumentParser(description="Check HEAD history for attribution trailers and generated-by signatures.")
    parser.add_argument("--root", type=Path, default=Path.cwd())
    args = parser.parse_args()
    report = check_history(args.root.resolve())
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
