#!/usr/bin/env python3
"""Attribution hygiene over the commit history reachable from HEAD.

Provenance: re-implements, from documented behaviour only, the attribution
half of the commit-gate doctrine that the consolidation inventory of
2026-09-19 (section 6) marked as the smallest agent-skills increment to land
in paes. No text or code was copied. The rule itself lives in
``policies/contribution.md``; this module is its enforcement and the runtime
default lives in project settings. Standard library only.

Rules, one issue code each, applied to every line of every message:

- ``attribution-trailer``: a line that opens with ``Co-Authored-By:`` or
  ``Signed-off-by:`` (case-insensitive).
- ``generated-signature``: a line that opens, after optional symbols or
  whitespace, with ``generated with`` or ``generated by`` (any case, hyphen or
  space between the words).

Findings name the commit and the rule, never the offending line, so a report
can be quoted without repeating what it rejects.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path

TRAILER_PATTERN = re.compile(r"^\s*(?:co-authored-by|signed-off-by)\s*:", re.IGNORECASE)
GENERATED_PATTERN = re.compile(r"^[\W_]*generated[- ](?:with|by)\b", re.IGNORECASE)

RECORD_SEPARATOR = "\x00"
FIELD_SEPARATOR = "\x1f"


def inspect_message(message: str) -> list[str]:
    """Return the sorted, de-duplicated issue codes for one full commit message."""
    issues: set[str] = set()
    for line in message.splitlines():
        if TRAILER_PATTERN.match(line):
            issues.add("attribution-trailer")
        if GENERATED_PATTERN.match(line):
            issues.add("generated-signature")
    return sorted(issues)


def read_history(root: Path) -> list[tuple[str, str]]:
    """Read (sha, full message) for every commit reachable from HEAD."""
    result = subprocess.run(
        ["git", "log", "HEAD", "-z", f"--format=%H{FIELD_SEPARATOR}%B"],
        cwd=root,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        if "does not have any commits yet" in result.stderr or "unknown revision" in result.stderr:
            return []
        raise RuntimeError(f"git log failed: {result.stderr.strip()}")
    commits: list[tuple[str, str]] = []
    for record in result.stdout.split(RECORD_SEPARATOR):
        if record:
            sha, message = record.split(FIELD_SEPARATOR, 1)
            commits.append((sha, message))
    return commits


def check_history(root: Path) -> dict[str, object]:
    """Inspect HEAD history and return a report with ``passed``, ``commits`` and ``findings``."""
    commits = read_history(root)
    findings = [
        {"commit": sha[:12], "rule": rule}
        for sha, message in commits
        for rule in inspect_message(message)
    ]
    return {"passed": not findings, "commits": len(commits), "findings": findings}


def main() -> int:
    parser = argparse.ArgumentParser(description="Check HEAD history for attribution trailers and generated-by signatures.")
    parser.add_argument("--root", type=Path, default=Path.cwd())
    args = parser.parse_args()
    report = check_history(args.root.resolve())
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
